fragment imageInfo on ImageExtended {
  alt
  asset {
    _id
    path
    metadata {
      dimensions {
        width
        height
      }
    }
    source {
      url
    }
  }
}

fragment teamSection on TeamSection {
  _type
  teamMembers {
    fullname
    role
    image {
      ...imageInfo
    }
    twitter
    github
    linkedin
    medium
  }
}
