fragment PostsParts on Posts {
  title
  body
}

fragment AppsParts on Apps {
  image
  title
  richtext
  website
  twitter
  discord
  linkedin
}

fragment VideosParts on Videos {
  image
  title
  richtext
  website
}

fragment Web3Parts on Web3 {
  image
  title
  richtext
  website
}

fragment StakingParts on Staking {
  image
  title
  richtext
  website
  twitter
  discord
  linkedin
}

fragment ExchangeParts on Exchange {
  image
  title
  richtext
  website
  twitter
  discord
  linkedin
}

fragment ComunityParts on Comunity {
  image
  title
  richtext
  website
}

fragment PagesParts on Pages {
  title
  updatedAt
  body
}

fragment EcosystemParts on Ecosystem {
  hero_title_dark
  hero_title_green
  hero_description
  hero_eyebrow
}
